apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-aws.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend-dev
  name: frontend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend-dev
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-aws.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: frontend-dev
    spec:
      containers:
        - env:
            - name: CHOKIDAR_USEPOLLING
              value: "true"
            - name: REACT_APP_GATEWAY_URI
              value: http://gateway:8071
          image: 848980285290.dkr.ecr.us-east-1.amazonaws.com/frontend:dev
          name: devfrontend
          ports:
            - containerPort: 3000
          resources: {}
          stdin: true
      restartPolicy: Always
status: {}
