apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-aws.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: identityservice
  name: identityservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: identityservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-aws.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: identityservice
    spec:
      containers:
        - env:
            - name: CONFIGSERVER_PORT
              value: "8071"
            - name: CONFIGSERVER_URI
              value: http://configserver:8071
            - name: PROFILE
              value: dev
          image: 848980285290.dkr.ecr.us-east-1.amazonaws.com/identityserver:dev
          name: identityservice
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
