server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      routes:
        - id: info-service
          uri: lb://info-service
          predicates:
            - Path=/info/**
          filters:
            - RemoveRequestHeader=Cookie,Set-Cookie
            - RewritePath=/info/(?<path>.*), /$\{path}
        - id: resource-service
          uri: lb://resource-service
          predicates:
            - Path=/resource/**
          filters:
            - RemoveRequestHeader=Cookie,Set-Cookie
            - RewritePath=/resource/(?<path>.*), /$\{path}
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/identity/**
          filters:
            - RewritePath=/identity/(?<path>.*), /$\{path}

logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG
        cloud:
          gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
