server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      routes:
        - id: info-service
          uri: lb://info-service
          predicates:
            - Path=/info/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/info/(?<path>.*), /$\{path}
        - id: resource-service
          uri: lb://resource-service
          predicates:
            - Path=/resource/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/resource/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      exposure:
        include: "*"
